# Generated by Django 3.0.3 on 2021-01-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
