# Generated by Django 3.0.3 on 2021-01-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
